version: '3.6'
services:
    nuxt_js:
        image: node:15.11.0-alpine3.10
        command: npm run dev
        volumes:
            - ./app:/usr/src/nuxt-app
        working_dir: /usr/src/nuxt-app
        ports:
            - 3001:3000
        environment:
            HOST: 0.0.0.0
